//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferencePPS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanQuantityModel", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService.Models")]
    public partial class PlanQuantityModel : object
    {
        
        private long IdLineField;
        
        private int MonthField;
        
        private string PartNoField;
        
        private System.Nullable<double> QuantityField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdLine
        {
            get
            {
                return this.IdLineField;
            }
            set
            {
                this.IdLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNo
        {
            get
            {
                return this.PartNoField;
            }
            set
            {
                this.PartNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigProductModel", Namespace="http://schemas.datacontract.org/2004/07/PPS.Models")]
    public partial class ConfigProductModel : object
    {
        
        private string AdvTermField;
        
        private int CountLineField;
        
        private System.Nullable<double> CurrentStockField;
        
        private string CustomerCodeField;
        
        private string CustomerPartNoField;
        
        private string DirectCustomerField;
        
        private bool DisableField;
        
        private string FinalCustomerField;
        
        private string FixedTermField;
        
        private string HjpPartNoField;
        
        private string ItemDescriptionField;
        
        private System.Nullable<double> JtField;
        
        private string[] ListLineField;
        
        private System.Nullable<double> LotSizeField;
        
        private int LotSizeEkanbanField;
        
        private System.Nullable<double> MaxStockField;
        
        private System.Nullable<double> MinStockField;
        
        private System.Nullable<double> PalletSizeField;
        
        private string PartNumberField;
        
        private double PendingQuantityField;
        
        private int PiorityField;
        
        private string ProcessCodeField;
        
        private string ProductNameField;
        
        private int QuantityPerKanbanField;
        
        private System.Nullable<double> RateField;
        
        private System.Nullable<int> SequenceEkanbanField;
        
        private System.Nullable<double> StockPolicyField;
        
        private string SymbolField;
        
        private int TypePackageField;
        
        private int TypePartField;
        
        private System.Nullable<double> UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdvTerm
        {
            get
            {
                return this.AdvTermField;
            }
            set
            {
                this.AdvTermField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountLine
        {
            get
            {
                return this.CountLineField;
            }
            set
            {
                this.CountLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CurrentStock
        {
            get
            {
                return this.CurrentStockField;
            }
            set
            {
                this.CurrentStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPartNo
        {
            get
            {
                return this.CustomerPartNoField;
            }
            set
            {
                this.CustomerPartNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectCustomer
        {
            get
            {
                return this.DirectCustomerField;
            }
            set
            {
                this.DirectCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disable
        {
            get
            {
                return this.DisableField;
            }
            set
            {
                this.DisableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalCustomer
        {
            get
            {
                return this.FinalCustomerField;
            }
            set
            {
                this.FinalCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FixedTerm
        {
            get
            {
                return this.FixedTermField;
            }
            set
            {
                this.FixedTermField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HjpPartNo
        {
            get
            {
                return this.HjpPartNoField;
            }
            set
            {
                this.HjpPartNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription
        {
            get
            {
                return this.ItemDescriptionField;
            }
            set
            {
                this.ItemDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Jt
        {
            get
            {
                return this.JtField;
            }
            set
            {
                this.JtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListLine
        {
            get
            {
                return this.ListLineField;
            }
            set
            {
                this.ListLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LotSize
        {
            get
            {
                return this.LotSizeField;
            }
            set
            {
                this.LotSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LotSizeEkanban
        {
            get
            {
                return this.LotSizeEkanbanField;
            }
            set
            {
                this.LotSizeEkanbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MaxStock
        {
            get
            {
                return this.MaxStockField;
            }
            set
            {
                this.MaxStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MinStock
        {
            get
            {
                return this.MinStockField;
            }
            set
            {
                this.MinStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PalletSize
        {
            get
            {
                return this.PalletSizeField;
            }
            set
            {
                this.PalletSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PendingQuantity
        {
            get
            {
                return this.PendingQuantityField;
            }
            set
            {
                this.PendingQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Piority
        {
            get
            {
                return this.PiorityField;
            }
            set
            {
                this.PiorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessCode
        {
            get
            {
                return this.ProcessCodeField;
            }
            set
            {
                this.ProcessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantityPerKanban
        {
            get
            {
                return this.QuantityPerKanbanField;
            }
            set
            {
                this.QuantityPerKanbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SequenceEkanban
        {
            get
            {
                return this.SequenceEkanbanField;
            }
            set
            {
                this.SequenceEkanbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StockPolicy
        {
            get
            {
                return this.StockPolicyField;
            }
            set
            {
                this.StockPolicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypePackage
        {
            get
            {
                return this.TypePackageField;
            }
            set
            {
                this.TypePackageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypePart
        {
            get
            {
                return this.TypePartField;
            }
            set
            {
                this.TypePartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigLineModel", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService.Models")]
    public partial class ConfigLineModel : object
    {
        
        private long IdLineField;
        
        private System.Nullable<double> JtField;
        
        private string PartNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdLine
        {
            get
            {
                return this.IdLineField;
            }
            set
            {
                this.IdLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Jt
        {
            get
            {
                return this.JtField;
            }
            set
            {
                this.JtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNo
        {
            get
            {
                return this.PartNoField;
            }
            set
            {
                this.PartNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusProduct", Namespace="http://schemas.datacontract.org/2004/07/PPS.Models")]
    public partial class StatusProduct : object
    {
        
        private string ProductNameField;
        
        private int StatusField;
        
        private ServiceReferencePPS.StatusPart[] StatusPartsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferencePPS.StatusPart[] StatusParts
        {
            get
            {
                return this.StatusPartsField;
            }
            set
            {
                this.StatusPartsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusPart", Namespace="http://schemas.datacontract.org/2004/07/PPS.Models")]
    public partial class StatusPart : object
    {
        
        private double ConfirmShippingField;
        
        private string DirectCustomerField;
        
        private System.Nullable<double> DohField;
        
        private string FinalCustomerField;
        
        private System.Nullable<double> MaxField;
        
        private System.Nullable<double> MinField;
        
        private string PartNumberField;
        
        private string ProductNameField;
        
        private System.Nullable<System.DateTime> ShippingDateField;
        
        private int StatusField;
        
        private double StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ConfirmShipping
        {
            get
            {
                return this.ConfirmShippingField;
            }
            set
            {
                this.ConfirmShippingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectCustomer
        {
            get
            {
                return this.DirectCustomerField;
            }
            set
            {
                this.DirectCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Doh
        {
            get
            {
                return this.DohField;
            }
            set
            {
                this.DohField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalCustomer
        {
            get
            {
                return this.FinalCustomerField;
            }
            set
            {
                this.FinalCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Max
        {
            get
            {
                return this.MaxField;
            }
            set
            {
                this.MaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Min
        {
            get
            {
                return this.MinField;
            }
            set
            {
                this.MinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippingDate
        {
            get
            {
                return this.ShippingDateField;
            }
            set
            {
                this.ShippingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusAllProduct", Namespace="http://schemas.datacontract.org/2004/07/PPS.Models")]
    public partial class StatusAllProduct : object
    {
        
        private System.Nullable<double> DohField;
        
        private int MonthField;
        
        private ServiceReferencePPS.StatusOfProduct[] StatusOfProductsField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Doh
        {
            get
            {
                return this.DohField;
            }
            set
            {
                this.DohField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferencePPS.StatusOfProduct[] StatusOfProducts
        {
            get
            {
                return this.StatusOfProductsField;
            }
            set
            {
                this.StatusOfProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusOfProduct", Namespace="http://schemas.datacontract.org/2004/07/PPS.Models")]
    public partial class StatusOfProduct : object
    {
        
        private System.Nullable<double> DohField;
        
        private System.Nullable<double> MaxField;
        
        private System.Nullable<double> MinField;
        
        private string ProductNameField;
        
        private ServiceReferencePPS.StatusPart[] StatusPartsField;
        
        private System.Nullable<double> TotalPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Doh
        {
            get
            {
                return this.DohField;
            }
            set
            {
                this.DohField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Max
        {
            get
            {
                return this.MaxField;
            }
            set
            {
                this.MaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Min
        {
            get
            {
                return this.MinField;
            }
            set
            {
                this.MinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferencePPS.StatusPart[] StatusParts
        {
            get
            {
                return this.StatusPartsField;
            }
            set
            {
                this.StatusPartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalPrice
        {
            get
            {
                return this.TotalPriceField;
            }
            set
            {
                this.TotalPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryStatusPart", Namespace="http://schemas.datacontract.org/2004/07/PPS.Models")]
    public partial class HistoryStatusPart : object
    {
        
        private System.DateTime DateField;
        
        private System.Nullable<double> DohField;
        
        private System.Nullable<double> MaxField;
        
        private System.Nullable<double> MinField;
        
        private string PartNumberField;
        
        private double StockPolicyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Doh
        {
            get
            {
                return this.DohField;
            }
            set
            {
                this.DohField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Max
        {
            get
            {
                return this.MaxField;
            }
            set
            {
                this.MaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Min
        {
            get
            {
                return this.MinField;
            }
            set
            {
                this.MinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StockPolicy
        {
            get
            {
                return this.StockPolicyField;
            }
            set
            {
                this.StockPolicyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineModel", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService")]
    public partial class LineModel : object
    {
        
        private long IdLineField;
        
        private string LineNameField;
        
        private string ProductNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdLine
        {
            get
            {
                return this.IdLineField;
            }
            set
            {
                this.IdLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineName
        {
            get
            {
                return this.LineNameField;
            }
            set
            {
                this.LineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartModel", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService")]
    public partial class PartModel : object
    {
        
        private string PartNumberField;
        
        private double RateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartLineModel", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService")]
    public partial class PartLineModel : object
    {
        
        private long IdLineField;
        
        private double JtField;
        
        private string PartNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdLine
        {
            get
            {
                return this.IdLineField;
            }
            set
            {
                this.IdLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Jt
        {
            get
            {
                return this.JtField;
            }
            set
            {
                this.JtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageLeadTime", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService.Models")]
    public partial class PackageLeadTime : object
    {
        
        private double MovingTimeField;
        
        private string PartNumberField;
        
        private double PreparingTimeField;
        
        private int TypePackageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MovingTime
        {
            get
            {
                return this.MovingTimeField;
            }
            set
            {
                this.MovingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PreparingTime
        {
            get
            {
                return this.PreparingTimeField;
            }
            set
            {
                this.PreparingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypePackage
        {
            get
            {
                return this.TypePackageField;
            }
            set
            {
                this.TypePackageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypePackage", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService.Models", IsReference=true)]
    public partial class TypePackage : ServiceReferencePPS.EntityObject
    {
        
        private string DescriptionField;
        
        private double MovingTimeField;
        
        private double PreparingTimeField;
        
        private int TypePackage1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MovingTime
        {
            get
            {
                return this.MovingTimeField;
            }
            set
            {
                this.MovingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PreparingTime
        {
            get
            {
                return this.PreparingTimeField;
            }
            set
            {
                this.PreparingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypePackage1
        {
            get
            {
                return this.TypePackage1Field;
            }
            set
            {
                this.TypePackage1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ManageProcessDailyPlan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.TypePackage))]
    public partial class StructuralObject : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ManageProcessDailyPlan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.TypePackage))]
    public partial class EntityObject : ServiceReferencePPS.StructuralObject
    {
        
        private ServiceReferencePPS.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferencePPS.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManageProcessDailyPlan", Namespace="http://schemas.datacontract.org/2004/07/PPS.WCFService.Models", IsReference=true)]
    public partial class ManageProcessDailyPlan : ServiceReferencePPS.EntityObject
    {
        
        private string ConfirmByField;
        
        private System.Nullable<System.DateTime> ConfirmDateField;
        
        private string CreateByField;
        
        private System.DateTime CreateDateField;
        
        private long IdLineField;
        
        private bool IsProcessField;
        
        private long NumberProcessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmBy
        {
            get
            {
                return this.ConfirmByField;
            }
            set
            {
                this.ConfirmByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConfirmDate
        {
            get
            {
                return this.ConfirmDateField;
            }
            set
            {
                this.ConfirmDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdLine
        {
            get
            {
                return this.IdLineField;
            }
            set
            {
                this.IdLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProcess
        {
            get
            {
                return this.IsProcessField;
            }
            set
            {
                this.IsProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumberProcess
        {
            get
            {
                return this.NumberProcessField;
            }
            set
            {
                this.NumberProcessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object
    {
        
        private string EntityContainerNameField;
        
        private ServiceReferencePPS.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName
        {
            get
            {
                return this.EntityContainerNameField;
            }
            set
            {
                this.EntityContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferencePPS.EntityKeyMember[] EntityKeyValues
        {
            get
            {
                return this.EntityKeyValuesField;
            }
            set
            {
                this.EntityKeyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName
        {
            get
            {
                return this.EntitySetNameField;
            }
            set
            {
                this.EntitySetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.LineModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.LineModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PartModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PartModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PartLineModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PartLineModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ConfigProductModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ConfigProductModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusProduct[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusPart[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusPart))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusAllProduct[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusAllProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusOfProduct[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.StatusOfProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.HistoryStatusPart[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.HistoryStatusPart))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(long[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PlanQuantityModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PlanQuantityModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ConfigLineModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ConfigLineModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PackageLeadTime[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.PackageLeadTime))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.TypePackage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.TypePackage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReferencePPS.ManageProcessDailyPlan))]
    public partial class EntityKeyMember : object
    {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePPS.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlan", ReplyAction="http://tempuri.org/IService1/UpdatePlanResponse")]
        System.Threading.Tasks.Task<int> UpdatePlanAsync(string partNumber, int quantity, long idLine, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdPlan", ReplyAction="http://tempuri.org/IService1/GetProdPlanResponse")]
        System.Threading.Tasks.Task<double> GetProdPlanAsync(string partNumber, System.DateTime date, long IdLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActualProd", ReplyAction="http://tempuri.org/IService1/GetActualProdResponse")]
        System.Threading.Tasks.Task<double> GetActualProdAsync(string partNumber, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMonthlyPlan", ReplyAction="http://tempuri.org/IService1/GetMonthlyPlanResponse")]
        System.Threading.Tasks.Task<double> GetMonthlyPlanAsync(string partNumber, int year, int month, long IdLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMonthlyPlanByLine", ReplyAction="http://tempuri.org/IService1/GetMonthlyPlanByLineResponse")]
        System.Threading.Tasks.Task<double> GetMonthlyPlanByLineAsync(int year, int month, long IdLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdPlanByLine", ReplyAction="http://tempuri.org/IService1/GetProdPlanByLineResponse")]
        System.Threading.Tasks.Task<double> GetProdPlanByLineAsync(System.DateTime date, long IdLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMonthlyPlanData", ReplyAction="http://tempuri.org/IService1/GetAllMonthlyPlanDataResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.PlanQuantityModel[]> GetAllMonthlyPlanDataAsync(long[] idLines, int pyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPartFromLine", ReplyAction="http://tempuri.org/IService1/GetListPartFromLineResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.ConfigProductModel[]> GetListPartFromLineAsync(long idLine, bool isAllPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPartFromListLine", ReplyAction="http://tempuri.org/IService1/GetListPartFromListLineResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.ConfigProductModel[]> GetListPartFromListLineAsync(long[] listIdLine, bool isAllPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListConfigLineFromListLine", ReplyAction="http://tempuri.org/IService1/GetListConfigLineFromListLineResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.ConfigLineModel[]> GetListConfigLineFromListLineAsync(long[] listIdLine, bool isAllPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListStatusProduct", ReplyAction="http://tempuri.org/IService1/GetListStatusProductResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.StatusProduct[]> GetListStatusProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListStatusAllProduct", ReplyAction="http://tempuri.org/IService1/GetListStatusAllProductResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.StatusAllProduct[]> GetListStatusAllProductAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStatusOfPartInRange", ReplyAction="http://tempuri.org/IService1/GetStatusOfPartInRangeResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.HistoryStatusPart[]> GetStatusOfPartInRangeAsync(string partNumber, System.DateTime froDateTime, System.DateTime endDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListLine", ReplyAction="http://tempuri.org/IService1/GetListLineResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.LineModel[]> GetListLineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListLineForVisualize", ReplyAction="http://tempuri.org/IService1/GetListLineForVisualizeResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.LineModel[]> GetListLineForVisualizeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetRateForPart", ReplyAction="http://tempuri.org/IService1/SetRateForPartResponse")]
        System.Threading.Tasks.Task<bool> SetRateForPartAsync(ServiceReferencePPS.PartModel[] lstPartModels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetJtForPart", ReplyAction="http://tempuri.org/IService1/SetJtForPartResponse")]
        System.Threading.Tasks.Task<bool> SetJtForPartAsync(ServiceReferencePPS.PartLineModel[] lstPartModels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExternalInfoFromPart", ReplyAction="http://tempuri.org/IService1/GetExternalInfoFromPartResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.PackageLeadTime[]> GetExternalInfoFromPartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTypePackageForPart", ReplyAction="http://tempuri.org/IService1/SetTypePackageForPartResponse")]
        System.Threading.Tasks.Task<bool> SetTypePackageForPartAsync(string partNumber, int typePackage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTimeForTypePackage", ReplyAction="http://tempuri.org/IService1/SetTimeForTypePackageResponse")]
        System.Threading.Tasks.Task<bool> SetTimeForTypePackageAsync(int typePackage, double preparingTime, double movingTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypePackage", ReplyAction="http://tempuri.org/IService1/GetTypePackageResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.TypePackage[]> GetTypePackageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListProductFromListPart", ReplyAction="http://tempuri.org/IService1/GetListProductFromListPartResponse")]
        System.Threading.Tasks.Task<string[]> GetListProductFromListPartAsync(string[] listPartNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListProduct", ReplyAction="http://tempuri.org/IService1/GetListProductResponse")]
        System.Threading.Tasks.Task<string[]> GetListProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetDohForPart", ReplyAction="http://tempuri.org/IService1/SetDohForPartResponse")]
        System.Threading.Tasks.Task<bool> SetDohForPartAsync(string partNumber, int month, int year, double doh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetProuctEkanbanSequenceForPart", ReplyAction="http://tempuri.org/IService1/SetProuctEkanbanSequenceForPartResponse")]
        System.Threading.Tasks.Task<bool> SetProuctEkanbanSequenceForPartAsync(string partNumber, int Idline, int sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastestDailyPlan", ReplyAction="http://tempuri.org/IService1/GetLastestDailyPlanResponse")]
        System.Threading.Tasks.Task<ServiceReferencePPS.ManageProcessDailyPlan> GetLastestDailyPlanAsync(int Idline);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListLineIsProcessing", ReplyAction="http://tempuri.org/IService1/GetListLineIsProcessingResponse")]
        System.Threading.Tasks.Task<long[]> GetListLineIsProcessingAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetShippingPlan", ReplyAction="http://tempuri.org/IService1/GetShippingPlanResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetShippingPlanAsync(double quantity, string partNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IService1Channel : ServiceReferencePPS.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReferencePPS.IService1>, ServiceReferencePPS.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> UpdatePlanAsync(string partNumber, int quantity, long idLine, System.DateTime date)
        {
            return base.Channel.UpdatePlanAsync(partNumber, quantity, idLine, date);
        }
        
        public System.Threading.Tasks.Task<double> GetProdPlanAsync(string partNumber, System.DateTime date, long IdLine)
        {
            return base.Channel.GetProdPlanAsync(partNumber, date, IdLine);
        }
        
        public System.Threading.Tasks.Task<double> GetActualProdAsync(string partNumber, System.DateTime date)
        {
            return base.Channel.GetActualProdAsync(partNumber, date);
        }
        
        public System.Threading.Tasks.Task<double> GetMonthlyPlanAsync(string partNumber, int year, int month, long IdLine)
        {
            return base.Channel.GetMonthlyPlanAsync(partNumber, year, month, IdLine);
        }
        
        public System.Threading.Tasks.Task<double> GetMonthlyPlanByLineAsync(int year, int month, long IdLine)
        {
            return base.Channel.GetMonthlyPlanByLineAsync(year, month, IdLine);
        }
        
        public System.Threading.Tasks.Task<double> GetProdPlanByLineAsync(System.DateTime date, long IdLine)
        {
            return base.Channel.GetProdPlanByLineAsync(date, IdLine);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.PlanQuantityModel[]> GetAllMonthlyPlanDataAsync(long[] idLines, int pyear)
        {
            return base.Channel.GetAllMonthlyPlanDataAsync(idLines, pyear);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.ConfigProductModel[]> GetListPartFromLineAsync(long idLine, bool isAllPart)
        {
            return base.Channel.GetListPartFromLineAsync(idLine, isAllPart);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.ConfigProductModel[]> GetListPartFromListLineAsync(long[] listIdLine, bool isAllPart)
        {
            return base.Channel.GetListPartFromListLineAsync(listIdLine, isAllPart);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.ConfigLineModel[]> GetListConfigLineFromListLineAsync(long[] listIdLine, bool isAllPart)
        {
            return base.Channel.GetListConfigLineFromListLineAsync(listIdLine, isAllPart);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.StatusProduct[]> GetListStatusProductAsync()
        {
            return base.Channel.GetListStatusProductAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.StatusAllProduct[]> GetListStatusAllProductAsync(int year)
        {
            return base.Channel.GetListStatusAllProductAsync(year);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.HistoryStatusPart[]> GetStatusOfPartInRangeAsync(string partNumber, System.DateTime froDateTime, System.DateTime endDateTime)
        {
            return base.Channel.GetStatusOfPartInRangeAsync(partNumber, froDateTime, endDateTime);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.LineModel[]> GetListLineAsync()
        {
            return base.Channel.GetListLineAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.LineModel[]> GetListLineForVisualizeAsync()
        {
            return base.Channel.GetListLineForVisualizeAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SetRateForPartAsync(ServiceReferencePPS.PartModel[] lstPartModels)
        {
            return base.Channel.SetRateForPartAsync(lstPartModels);
        }
        
        public System.Threading.Tasks.Task<bool> SetJtForPartAsync(ServiceReferencePPS.PartLineModel[] lstPartModels)
        {
            return base.Channel.SetJtForPartAsync(lstPartModels);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.PackageLeadTime[]> GetExternalInfoFromPartAsync()
        {
            return base.Channel.GetExternalInfoFromPartAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SetTypePackageForPartAsync(string partNumber, int typePackage)
        {
            return base.Channel.SetTypePackageForPartAsync(partNumber, typePackage);
        }
        
        public System.Threading.Tasks.Task<bool> SetTimeForTypePackageAsync(int typePackage, double preparingTime, double movingTime)
        {
            return base.Channel.SetTimeForTypePackageAsync(typePackage, preparingTime, movingTime);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.TypePackage[]> GetTypePackageAsync()
        {
            return base.Channel.GetTypePackageAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetListProductFromListPartAsync(string[] listPartNumber)
        {
            return base.Channel.GetListProductFromListPartAsync(listPartNumber);
        }
        
        public System.Threading.Tasks.Task<string[]> GetListProductAsync()
        {
            return base.Channel.GetListProductAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SetDohForPartAsync(string partNumber, int month, int year, double doh)
        {
            return base.Channel.SetDohForPartAsync(partNumber, month, year, doh);
        }
        
        public System.Threading.Tasks.Task<bool> SetProuctEkanbanSequenceForPartAsync(string partNumber, int Idline, int sequence)
        {
            return base.Channel.SetProuctEkanbanSequenceForPartAsync(partNumber, Idline, sequence);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePPS.ManageProcessDailyPlan> GetLastestDailyPlanAsync(int Idline)
        {
            return base.Channel.GetLastestDailyPlanAsync(Idline);
        }
        
        public System.Threading.Tasks.Task<long[]> GetListLineIsProcessingAsync(System.DateTime date)
        {
            return base.Channel.GetListLineIsProcessingAsync(date);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetShippingPlanAsync(double quantity, string partNumber)
        {
            return base.Channel.GetShippingPlanAsync(quantity, partNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://10.73.131.20:1234/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
