//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message_Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASP.Resources.Message.Shared", typeof(Message_Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("\\", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string lbl_account {
            get {
                return ResourceManager.GetString("lbl_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_location_mix {
            get {
                return ResourceManager.GetString("lbl_enum_location_mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_location_warehouse {
            get {
                return ResourceManager.GetString("lbl_enum_location_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_location_wip {
            get {
                return ResourceManager.GetString("lbl_enum_location_wip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_user_active {
            get {
                return ResourceManager.GetString("lbl_enum_status_user_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_user_in_active {
            get {
                return ResourceManager.GetString("lbl_enum_status_user_in_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_user_pending {
            get {
                return ResourceManager.GetString("lbl_enum_status_user_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_re_password {
            get {
                return ResourceManager.GetString("lbl_re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_account_max_length {
            get {
                return ResourceManager.GetString("msg_err_account_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_account_min_length {
            get {
                return ResourceManager.GetString("msg_err_account_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_author_max_length {
            get {
                return ResourceManager.GetString("msg_err_author_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_company_code_max_length {
            get {
                return ResourceManager.GetString("msg_err_company_code_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_company_id_max_length {
            get {
                return ResourceManager.GetString("msg_err_company_id_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_company_name_max_length {
            get {
                return ResourceManager.GetString("msg_err_company_name_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_company_short_name_max_length {
            get {
                return ResourceManager.GetString("msg_err_company_short_name_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_description_max_length {
            get {
                return ResourceManager.GetString("msg_err_description_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_fullname_max_length {
            get {
                return ResourceManager.GetString("msg_err_fullname_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_ip_address_max_length {
            get {
                return ResourceManager.GetString("msg_err_ip_address_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_log_content_max_length {
            get {
                return ResourceManager.GetString("msg_err_log_content_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_log_type_max_length {
            get {
                return ResourceManager.GetString("msg_err_log_type_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_menu_content_max_length {
            get {
                return ResourceManager.GetString("msg_err_menu_content_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_menu_description_max_length {
            get {
                return ResourceManager.GetString("msg_err_menu_description_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_menu_language_max_length {
            get {
                return ResourceManager.GetString("msg_err_menu_language_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_menu_title_max_length {
            get {
                return ResourceManager.GetString("msg_err_menu_title_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_partnumber_customer_max_length {
            get {
                return ResourceManager.GetString("msg_err_partnumber_customer_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_partnumber_customer_short_max_length {
            get {
                return ResourceManager.GetString("msg_err_partnumber_customer_short_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_partnumer_max_length {
            get {
                return ResourceManager.GetString("msg_err_partnumer_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_password_max_length {
            get {
                return ResourceManager.GetString("msg_err_password_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_password_min_length {
            get {
                return ResourceManager.GetString("msg_err_password_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_product_name_max_length {
            get {
                return ResourceManager.GetString("msg_err_product_name_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_re_password_max_length {
            get {
                return ResourceManager.GetString("msg_err_re_password_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_re_password_min_length {
            get {
                return ResourceManager.GetString("msg_err_re_password_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_re_password_not_match {
            get {
                return ResourceManager.GetString("msg_err_re_password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_role_name_max_length {
            get {
                return ResourceManager.GetString("msg_err_role_name_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_err_string_required {
            get {
                return ResourceManager.GetString("msg_err_string_required", resourceCulture);
            }
        }
    }
}
