//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASP.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_account {
            get {
                return ResourceManager.GetString("lbl_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_account_type {
            get {
                return ResourceManager.GetString("lbl_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_author {
            get {
                return ResourceManager.GetString("lbl_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_avatar {
            get {
                return ResourceManager.GetString("lbl_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_content {
            get {
                return ResourceManager.GetString("lbl_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_content_attachment {
            get {
                return ResourceManager.GetString("lbl_content_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_created_date {
            get {
                return ResourceManager.GetString("lbl_created_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_day_off {
            get {
                return ResourceManager.GetString("lbl_day_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_description {
            get {
                return ResourceManager.GetString("lbl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_email {
            get {
                return ResourceManager.GetString("lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_approval_approved {
            get {
                return ResourceManager.GetString("lbl_enum_approval_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_approval_cancel {
            get {
                return ResourceManager.GetString("lbl_enum_approval_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_approval_pending {
            get {
                return ResourceManager.GetString("lbl_enum_approval_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_approval_rejected {
            get {
                return ResourceManager.GetString("lbl_enum_approval_rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_level_approve_approve {
            get {
                return ResourceManager.GetString("lbl_enum_level_approve_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_level_approve_check {
            get {
                return ResourceManager.GetString("lbl_enum_level_approve_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_level_approve_none {
            get {
                return ResourceManager.GetString("lbl_enum_level_approve_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_location_mix {
            get {
                return ResourceManager.GetString("lbl_enum_location_mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_location_warehouse {
            get {
                return ResourceManager.GetString("lbl_enum_location_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_location_wip {
            get {
                return ResourceManager.GetString("lbl_enum_location_wip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_active_active {
            get {
                return ResourceManager.GetString("lbl_enum_status_active_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_active_disable {
            get {
                return ResourceManager.GetString("lbl_enum_status_active_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_user_active {
            get {
                return ResourceManager.GetString("lbl_enum_status_user_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_user_in_active {
            get {
                return ResourceManager.GetString("lbl_enum_status_user_in_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_status_user_pending {
            get {
                return ResourceManager.GetString("lbl_enum_status_user_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_type_change_create {
            get {
                return ResourceManager.GetString("lbl_enum_type_change_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_type_change_delete {
            get {
                return ResourceManager.GetString("lbl_enum_type_change_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_type_change_update {
            get {
                return ResourceManager.GetString("lbl_enum_type_change_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_user_type_acc {
            get {
                return ResourceManager.GetString("lbl_enum_user_type_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_user_type_none {
            get {
                return ResourceManager.GetString("lbl_enum_user_type_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_user_type_pc {
            get {
                return ResourceManager.GetString("lbl_enum_user_type_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_enum_user_type_pro {
            get {
                return ResourceManager.GetString("lbl_enum_user_type_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_from {
            get {
                return ResourceManager.GetString("lbl_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_fullname {
            get {
                return ResourceManager.GetString("lbl_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_group_mix_group_name {
            get {
                return ResourceManager.GetString("lbl_group_mix_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_ip_address {
            get {
                return ResourceManager.GetString("lbl_ip_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_issued_by {
            get {
                return ResourceManager.GetString("lbl_issued_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_kanban_attachment {
            get {
                return ResourceManager.GetString("lbl_kanban_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_kanban_no {
            get {
                return ResourceManager.GetString("lbl_kanban_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_language {
            get {
                return ResourceManager.GetString("lbl_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_log_type {
            get {
                return ResourceManager.GetString("lbl_log_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_phone_number {
            get {
                return ResourceManager.GetString("lbl_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_box_size {
            get {
                return ResourceManager.GetString("lbl_product_box_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_line_name {
            get {
                return ResourceManager.GetString("lbl_product_line_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_location {
            get {
                return ResourceManager.GetString("lbl_product_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_part_name {
            get {
                return ResourceManager.GetString("lbl_product_part_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_part_no {
            get {
                return ResourceManager.GetString("lbl_product_part_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_process_code {
            get {
                return ResourceManager.GetString("lbl_product_process_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_product_unit_type {
            get {
                return ResourceManager.GetString("lbl_product_unit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_quantity {
            get {
                return ResourceManager.GetString("lbl_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_re_password {
            get {
                return ResourceManager.GetString("lbl_re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_reason {
            get {
                return ResourceManager.GetString("lbl_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_role {
            get {
                return ResourceManager.GetString("lbl_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_role_count_user {
            get {
                return ResourceManager.GetString("lbl_role_count_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_role_default {
            get {
                return ResourceManager.GetString("lbl_role_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_role_permission {
            get {
                return ResourceManager.GetString("lbl_role_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_sample_text {
            get {
                return ResourceManager.GetString("lbl_sample_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_status {
            get {
                return ResourceManager.GetString("lbl_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_theme_name {
            get {
                return ResourceManager.GetString("lbl_theme_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_title {
            get {
                return ResourceManager.GetString("lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_to {
            get {
                return ResourceManager.GetString("lbl_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_type_change {
            get {
                return ResourceManager.GetString("lbl_type_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_updated_by {
            get {
                return ResourceManager.GetString("lbl_updated_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbl_updated_date {
            get {
                return ResourceManager.GetString("lbl_updated_date", resourceCulture);
            }
        }
    }
}
