//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceCommon
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailInfo", Namespace="http://schemas.datacontract.org/2004/07/Dmvn.Common.Service.DataContract")]
    public partial class EmailInfo : object
    {
        
        private string EmailAddressField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayInfo", Namespace="http://schemas.datacontract.org/2004/07/Dmvn.Common.Service.DataContract")]
    public partial class HolidayInfo : object
    {
        
        private System.DateTime DayField;
        
        private string DesciptionField;
        
        private int TypeHolidayField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Day
        {
            get
            {
                return this.DayField;
            }
            set
            {
                this.DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desciption
        {
            get
            {
                return this.DesciptionField;
            }
            set
            {
                this.DesciptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeHoliday
        {
            get
            {
                return this.TypeHolidayField;
            }
            set
            {
                this.TypeHolidayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/Dmvn.Common.Service.DataContract")]
    public partial class EmployeeInfo : object
    {
        
        private int DepartmentIdField;
        
        private int DivisionIdField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        private bool OffFacField;
        
        private int PositionIdField;
        
        private int SectionIdField;
        
        private bool SexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionId
        {
            get
            {
                return this.DivisionIdField;
            }
            set
            {
                this.DivisionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OffFac
        {
            get
            {
                return this.OffFacField;
            }
            set
            {
                this.OffFacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionId
        {
            get
            {
                return this.PositionIdField;
            }
            set
            {
                this.PositionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId
        {
            get
            {
                return this.SectionIdField;
            }
            set
            {
                this.SectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneBookInfo", Namespace="http://schemas.datacontract.org/2004/07/Dmvn.Common.Service.DataContract")]
    public partial class PhoneBookInfo : object
    {
        
        private int DepartmentIdField;
        
        private string DepartmentNameField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        private string NoteField;
        
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BodInfo", Namespace="http://schemas.datacontract.org/2004/07/Dmvn.Common.Service.DataContract")]
    public partial class BodInfo : object
    {
        
        private string BodCodeField;
        
        private string EmailAddressField;
        
        private string FullNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodCode
        {
            get
            {
                return this.BodCodeField;
            }
            set
            {
                this.BodCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCommon.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailFromCode", ReplyAction="http://tempuri.org/IService1/GetEmailFromCodeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.EmailInfo> GetEmailFromCodeAsync(string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllEmail", ReplyAction="http://tempuri.org/IService1/GetAllEmailResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.EmailInfo[]> GetAllEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHolidayFromYear", ReplyAction="http://tempuri.org/IService1/GetHolidayFromYearResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHolidayFromYearDc", ReplyAction="http://tempuri.org/IService1/GetHolidayFromYearDcResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearDcAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHolidayFromYearOffice", ReplyAction="http://tempuri.org/IService1/GetHolidayFromYearOfficeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearOfficeAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHolidayFromYearFac", ReplyAction="http://tempuri.org/IService1/GetHolidayFromYearFacResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearFacAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployeeInfoFromCode", ReplyAction="http://tempuri.org/IService1/GetEmployeeInfoFromCodeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.EmployeeInfo> GetEmployeeInfoFromCodeAsync(string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhoneFromCode", ReplyAction="http://tempuri.org/IService1/GetPhoneFromCodeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.PhoneBookInfo> GetPhoneFromCodeAsync(string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBodInfoFromCode", ReplyAction="http://tempuri.org/IService1/GetBodInfoFromCodeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.BodInfo> GetBodInfoFromCodeAsync(string bodCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBodInfos", ReplyAction="http://tempuri.org/IService1/GetBodInfosResponse")]
        System.Threading.Tasks.Task<ServiceReferenceCommon.BodInfo[]> GetBodInfosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IService1Channel : ServiceReferenceCommon.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReferenceCommon.IService1>, ServiceReferenceCommon.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.EmailInfo> GetEmailFromCodeAsync(string employeeId)
        {
            return base.Channel.GetEmailFromCodeAsync(employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.EmailInfo[]> GetAllEmailAsync()
        {
            return base.Channel.GetAllEmailAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearAsync(int year)
        {
            return base.Channel.GetHolidayFromYearAsync(year);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearDcAsync(int year)
        {
            return base.Channel.GetHolidayFromYearDcAsync(year);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearOfficeAsync(int year)
        {
            return base.Channel.GetHolidayFromYearOfficeAsync(year);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.HolidayInfo[]> GetHolidayFromYearFacAsync(int year)
        {
            return base.Channel.GetHolidayFromYearFacAsync(year);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.EmployeeInfo> GetEmployeeInfoFromCodeAsync(string employeeId)
        {
            return base.Channel.GetEmployeeInfoFromCodeAsync(employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.PhoneBookInfo> GetPhoneFromCodeAsync(string employeeId)
        {
            return base.Channel.GetPhoneFromCodeAsync(employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.BodInfo> GetBodInfoFromCodeAsync(string bodCode)
        {
            return base.Channel.GetBodInfoFromCodeAsync(bodCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCommon.BodInfo[]> GetBodInfosAsync()
        {
            return base.Channel.GetBodInfosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://10.73.131.20:9001/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
