//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEz
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DivisionInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class DivisionInfo : object
    {
        
        private string DivisionCodeField;
        
        private int DivisionIDField;
        
        private string DivisionNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionCode
        {
            get
            {
                return this.DivisionCodeField;
            }
            set
            {
                this.DivisionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class DepartmentInfo : object
    {
        
        private string DepartmentCodeField;
        
        private int DepartmentIDField;
        
        private string DepartmentNameField;
        
        private int DivisionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentCode
        {
            get
            {
                return this.DepartmentCodeField;
            }
            set
            {
                this.DepartmentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SectionInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class SectionInfo : object
    {
        
        private int DepartmentIDField;
        
        private string SectionCodeField;
        
        private int SectionIDField;
        
        private string SectionNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionCode
        {
            get
            {
                return this.SectionCodeField;
            }
            set
            {
                this.SectionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID
        {
            get
            {
                return this.SectionIDField;
            }
            set
            {
                this.SectionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionName
        {
            get
            {
                return this.SectionNameField;
            }
            set
            {
                this.SectionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class EmployeeInfo : object
    {
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private int DepartmentIDField;
        
        private int DivisionIDField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        private string GradeField;
        
        private System.Nullable<System.DateTime> HireDateField;
        
        private byte[] PhotoImageField;
        
        private int PositionIDField;
        
        private string PositionNameField;
        
        private System.Nullable<int> PriorityField;
        
        private System.Nullable<bool> ProductField;
        
        private int SectionIDField;
        
        private System.Nullable<bool> SexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade
        {
            get
            {
                return this.GradeField;
            }
            set
            {
                this.GradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HireDate
        {
            get
            {
                return this.HireDateField;
            }
            set
            {
                this.HireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PhotoImage
        {
            get
            {
                return this.PhotoImageField;
            }
            set
            {
                this.PhotoImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionID
        {
            get
            {
                return this.PositionIDField;
            }
            set
            {
                this.PositionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName
        {
            get
            {
                return this.PositionNameField;
            }
            set
            {
                this.PositionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID
        {
            get
            {
                return this.SectionIDField;
            }
            set
            {
                this.SectionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttendInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class AttendInfo : object
    {
        
        private System.DateTime AttDateField;
        
        private System.Nullable<System.DateTime> AttEndField;
        
        private System.Nullable<System.DateTime> AttStartField;
        
        private int ConfirmAttendField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        private double HourInShiftField;
        
        private double HourNpField;
        
        private double HourOtField;
        
        private int ShiftIdField;
        
        private System.Nullable<int> StatusOtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AttDate
        {
            get
            {
                return this.AttDateField;
            }
            set
            {
                this.AttDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AttEnd
        {
            get
            {
                return this.AttEndField;
            }
            set
            {
                this.AttEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AttStart
        {
            get
            {
                return this.AttStartField;
            }
            set
            {
                this.AttStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfirmAttend
        {
            get
            {
                return this.ConfirmAttendField;
            }
            set
            {
                this.ConfirmAttendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HourInShift
        {
            get
            {
                return this.HourInShiftField;
            }
            set
            {
                this.HourInShiftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HourNp
        {
            get
            {
                return this.HourNpField;
            }
            set
            {
                this.HourNpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HourOt
        {
            get
            {
                return this.HourOtField;
            }
            set
            {
                this.HourOtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShiftId
        {
            get
            {
                return this.ShiftIdField;
            }
            set
            {
                this.ShiftIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusOt
        {
            get
            {
                return this.StatusOtField;
            }
            set
            {
                this.StatusOtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class PositionInfo : object
    {
        
        private string PositionCodeField;
        
        private int PositionIdField;
        
        private string PositionNameField;
        
        private System.Nullable<int> PriorityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionCode
        {
            get
            {
                return this.PositionCodeField;
            }
            set
            {
                this.PositionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionId
        {
            get
            {
                return this.PositionIdField;
            }
            set
            {
                this.PositionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName
        {
            get
            {
                return this.PositionNameField;
            }
            set
            {
                this.PositionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkScheduleInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class WorkScheduleInfo : object
    {
        
        private string EmployeeIDField;
        
        private int HolidayStatusField;
        
        private int LeaveStatusField;
        
        private System.DateTime ScheduleDateField;
        
        private int ShiftIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                this.EmployeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HolidayStatus
        {
            get
            {
                return this.HolidayStatusField;
            }
            set
            {
                this.HolidayStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveStatus
        {
            get
            {
                return this.LeaveStatusField;
            }
            set
            {
                this.LeaveStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduleDate
        {
            get
            {
                return this.ScheduleDateField;
            }
            set
            {
                this.ScheduleDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShiftID
        {
            get
            {
                return this.ShiftIDField;
            }
            set
            {
                this.ShiftIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeAttendenInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class TimeAttendenInfo : object
    {
        
        private System.DateTime AttDateField;
        
        private string AttStatusField;
        
        private string EmpployeeIdField;
        
        private string FullNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AttDate
        {
            get
            {
                return this.AttDateField;
            }
            set
            {
                this.AttDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttStatus
        {
            get
            {
                return this.AttStatusField;
            }
            set
            {
                this.AttStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpployeeId
        {
            get
            {
                return this.EmpployeeIdField;
            }
            set
            {
                this.EmpployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeAttenden", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class TimeAttenden : object
    {
        
        private System.DateTime AttDateField;
        
        private string EmployeeIdField;
        
        private System.DateTime FromTimeField;
        
        private int ShiftIdField;
        
        private System.DateTime ToTimeField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AttDate
        {
            get
            {
                return this.AttDateField;
            }
            set
            {
                this.AttDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromTime
        {
            get
            {
                return this.FromTimeField;
            }
            set
            {
                this.FromTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShiftId
        {
            get
            {
                return this.ShiftIdField;
            }
            set
            {
                this.ShiftIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToTime
        {
            get
            {
                return this.ToTimeField;
            }
            set
            {
                this.ToTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeePropation", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class EmployeePropation : object
    {
        
        private int DepartmentIDField;
        
        private int DivisionIDField;
        
        private string EmployeeIdField;
        
        private System.DateTime EndDateField;
        
        private string FullNameField;
        
        private int SectionIDField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID
        {
            get
            {
                return this.SectionIDField;
            }
            set
            {
                this.SectionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeTerminate", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class EmployeeTerminate : object
    {
        
        private int DepartmentIDField;
        
        private int DivisionIDField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        private string LeaveCodeField;
        
        private int SectionIDField;
        
        private System.DateTime TerminateDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeaveCode
        {
            get
            {
                return this.LeaveCodeField;
            }
            set
            {
                this.LeaveCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID
        {
            get
            {
                return this.SectionIDField;
            }
            set
            {
                this.SectionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TerminateDate
        {
            get
            {
                return this.TerminateDateField;
            }
            set
            {
                this.TerminateDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabourContractInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class LabourContractInfo : object
    {
        
        private System.Nullable<System.DateTime> ContractEndDayField;
        
        private string ContractNoField;
        
        private System.Nullable<System.DateTime> ContractStartDayField;
        
        private System.Nullable<double> DurationField;
        
        private string EmployeeIdField;
        
        private string TypeLabourField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ContractEndDay
        {
            get
            {
                return this.ContractEndDayField;
            }
            set
            {
                this.ContractEndDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNo
        {
            get
            {
                return this.ContractNoField;
            }
            set
            {
                this.ContractNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ContractStartDay
        {
            get
            {
                return this.ContractStartDayField;
            }
            set
            {
                this.ContractStartDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeLabour
        {
            get
            {
                return this.TypeLabourField;
            }
            set
            {
                this.TypeLabourField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaveInfo", Namespace="http://schemas.datacontract.org/2004/07/ManPower.Ez.Service.Lib.DataContracts")]
    public partial class LeaveInfo : object
    {
        
        private System.Nullable<int> DepartmentIDField;
        
        private int DivisionIDField;
        
        private string EmployeeIdField;
        
        private string FullNameField;
        
        private string LeaveCodeField;
        
        private System.DateTime LeaveDateField;
        
        private int LeaveTypeField;
        
        private System.Nullable<int> SectionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeaveCode
        {
            get
            {
                return this.LeaveCodeField;
            }
            set
            {
                this.LeaveCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LeaveDate
        {
            get
            {
                return this.LeaveDateField;
            }
            set
            {
                this.LeaveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveType
        {
            get
            {
                return this.LeaveTypeField;
            }
            set
            {
                this.LeaveTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SectionID
        {
            get
            {
                return this.SectionIDField;
            }
            set
            {
                this.SectionIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEz.IServiceManPowerEz")]
    public interface IServiceManPowerEz
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetHello", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetHelloResponse")]
        System.Threading.Tasks.Task<string> GetHelloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetDivisionList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetDivisionListResponse")]
        System.Threading.Tasks.Task<ServiceEz.DivisionInfo[]> GetDivisionListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetDepartmentList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetDepartmentListResponse")]
        System.Threading.Tasks.Task<ServiceEz.DepartmentInfo[]> GetDepartmentListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetSectionList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetSectionListResponse")]
        System.Threading.Tasks.Task<ServiceEz.SectionInfo[]> GetSectionListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeInfo", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeInfoResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo> GetEmployeeInfoAsync(string employeeId, bool haveImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeAll", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeAllResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeAllAsync(bool haveLeaved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeListResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListAsync(int divisionId, int departmentId, int sectionId, bool haveImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAttendInfo", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAttendInfoResponse")]
        System.Threading.Tasks.Task<ServiceEz.AttendInfo> GetAttendInfoAsync(string employeeId, System.DateTime dateAtt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAttendInfoList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAttendInfoListResponse")]
        System.Threading.Tasks.Task<ServiceEz.AttendInfo[]> GetAttendInfoListAsync(string[] employees, System.DateTime dateAtt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAttendInfoListOld", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAttendInfoListOldResponse")]
        System.Threading.Tasks.Task<ServiceEz.AttendInfo[]> GetAttendInfoListOldAsync(string[] employees, System.DateTime dateAtt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAttendOfMonth", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAttendOfMonthResponse")]
        System.Threading.Tasks.Task<ServiceEz.AttendInfo[]> GetAttendOfMonthAsync(string employees, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeListWithArr", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeListWithArrResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListWithArrAsync(int[] divisionId, int[] departmentId, int[] sectionId, bool haveImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeListWithArrDate", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeListWithArrDateResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListWithArrDateAsync(int[] divisionId, int[] departmentId, int[] sectionId, System.DateTime dateAtt, bool haveImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetLeaveEmployeeList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetLeaveEmployeeListResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetLeaveEmployeeListAsync(int[] divisionId, int[] departmentId, bool haveImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeListPaySlip", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeListPaySlipResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListPaySlipAsync(int divisionId, int departmentId, int sectionId, System.DateTime dtGetData, bool haveImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAllPositionInfos", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAllPositionInfosResponse")]
        System.Threading.Tasks.Task<ServiceEz.PositionInfo[]> GetAllPositionInfosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeWithPositionAndDepartment", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeWithPositionAndDepartmentRespons" +
            "e")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeWithPositionAndDepartmentAsync(int divisionId, System.Nullable<int> departmentId, System.Nullable<int> sectionId, ServiceEz.PositionInfo[] listPositionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeInfoByCardId", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeInfoByCardIdResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo> GetEmployeeInfoByCardIdAsync(string cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/SyncWorkSchedule", ReplyAction="http://tempuri.org/IServiceManPowerEz/SyncWorkScheduleResponse")]
        System.Threading.Tasks.Task<ServiceEz.WorkScheduleInfo[]> SyncWorkScheduleAsync(ServiceEz.WorkScheduleInfo[] list, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetTimeAttendenInfos", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetTimeAttendenInfosResponse")]
        System.Threading.Tasks.Task<ServiceEz.TimeAttendenInfo[]> GetTimeAttendenInfosAsync(string employeeId, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/UpdateTimeAttenden", ReplyAction="http://tempuri.org/IServiceManPowerEz/UpdateTimeAttendenResponse")]
        System.Threading.Tasks.Task<bool> UpdateTimeAttendenAsync(ServiceEz.TimeAttenden timeAttenden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/UpdateWorkSchedule", ReplyAction="http://tempuri.org/IServiceManPowerEz/UpdateWorkScheduleResponse")]
        System.Threading.Tasks.Task<bool> UpdateWorkScheduleAsync(ServiceEz.WorkScheduleInfo scheduleInfo, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeNotInList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeNotInListResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeNotInListAsync(string[] employees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeInList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeInListResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeInListAsync(string[] listEmployeeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAllEmployeeInListHasImage", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAllEmployeeInListHasImageResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetAllEmployeeInListHasImageAsync(string[] listEmployeeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeChangeDept", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeChangeDeptResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeChangeDeptAsync(System.DateTime fromDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeePropation", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeePropationResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeePropation[]> GetEmployeePropationAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeNotHavingPropation", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeNotHavingPropationResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeePropation[]> GetEmployeeNotHavingPropationAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeTerminate", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeTerminateResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeTerminate[]> GetEmployeeTerminateAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeePrivateLeaveWithoutReport", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeePrivateLeaveWithoutReportRespons" +
            "e")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeTerminate[]> GetEmployeePrivateLeaveWithoutReportAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeWithoutScanCard", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeWithoutScanCardResponse")]
        System.Threading.Tasks.Task<ServiceEz.TimeAttendenInfo[]> GetEmployeeWithoutScanCardAsync(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetInfoLabourContract", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetInfoLabourContractResponse")]
        System.Threading.Tasks.Task<ServiceEz.LabourContractInfo> GetInfoLabourContractAsync(string employeeId, System.DateTime fromBusinessDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetInfoLabourContractProbation", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetInfoLabourContractProbationResponse")]
        System.Threading.Tasks.Task<ServiceEz.LabourContractInfo> GetInfoLabourContractProbationAsync(string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeJapan", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeJapanResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeJapanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetLeaveInfoInMonth", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetLeaveInfoInMonthResponse")]
        System.Threading.Tasks.Task<ServiceEz.LeaveInfo[]> GetLeaveInfoInMonthAsync(System.DateTime month, int divisionId, int departmentId, int sectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetAllEmployeeInList", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetAllEmployeeInListResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetAllEmployeeInListAsync(string[] listEmployeeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetEmployeeListAddTerminateOnMonth", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetEmployeeListAddTerminateOnMonthResponse")]
        System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListAddTerminateOnMonthAsync(int divisionId, int departmentId, int sectionId, System.DateTime month, string employeeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/CheckHd1WSchedule", ReplyAction="http://tempuri.org/IServiceManPowerEz/CheckHd1WScheduleResponse")]
        System.Threading.Tasks.Task<double> CheckHd1WScheduleAsync(string employeeId, System.DateTime dtHd1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/CheckAccountAd", ReplyAction="http://tempuri.org/IServiceManPowerEz/CheckAccountAdResponse")]
        System.Threading.Tasks.Task<bool> CheckAccountAdAsync(string uName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceManPowerEz/GetTimeAttendens", ReplyAction="http://tempuri.org/IServiceManPowerEz/GetTimeAttendensResponse")]
        System.Threading.Tasks.Task<ServiceEz.TimeAttenden[]> GetTimeAttendensAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceManPowerEzChannel : ServiceEz.IServiceManPowerEz, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceManPowerEzClient : System.ServiceModel.ClientBase<ServiceEz.IServiceManPowerEz>, ServiceEz.IServiceManPowerEz
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceManPowerEzClient() : 
                base(ServiceManPowerEzClient.GetDefaultBinding(), ServiceManPowerEzClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceManPowerEz.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceManPowerEzClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceManPowerEzClient.GetBindingForEndpoint(endpointConfiguration), ServiceManPowerEzClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceManPowerEzClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceManPowerEzClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceManPowerEzClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceManPowerEzClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceManPowerEzClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetHelloAsync()
        {
            return base.Channel.GetHelloAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceEz.DivisionInfo[]> GetDivisionListAsync()
        {
            return base.Channel.GetDivisionListAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceEz.DepartmentInfo[]> GetDepartmentListAsync()
        {
            return base.Channel.GetDepartmentListAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceEz.SectionInfo[]> GetSectionListAsync()
        {
            return base.Channel.GetSectionListAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo> GetEmployeeInfoAsync(string employeeId, bool haveImage)
        {
            return base.Channel.GetEmployeeInfoAsync(employeeId, haveImage);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeAllAsync(bool haveLeaved)
        {
            return base.Channel.GetEmployeeAllAsync(haveLeaved);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListAsync(int divisionId, int departmentId, int sectionId, bool haveImage)
        {
            return base.Channel.GetEmployeeListAsync(divisionId, departmentId, sectionId, haveImage);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.AttendInfo> GetAttendInfoAsync(string employeeId, System.DateTime dateAtt)
        {
            return base.Channel.GetAttendInfoAsync(employeeId, dateAtt);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.AttendInfo[]> GetAttendInfoListAsync(string[] employees, System.DateTime dateAtt)
        {
            return base.Channel.GetAttendInfoListAsync(employees, dateAtt);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.AttendInfo[]> GetAttendInfoListOldAsync(string[] employees, System.DateTime dateAtt)
        {
            return base.Channel.GetAttendInfoListOldAsync(employees, dateAtt);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.AttendInfo[]> GetAttendOfMonthAsync(string employees, System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetAttendOfMonthAsync(employees, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListWithArrAsync(int[] divisionId, int[] departmentId, int[] sectionId, bool haveImage)
        {
            return base.Channel.GetEmployeeListWithArrAsync(divisionId, departmentId, sectionId, haveImage);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListWithArrDateAsync(int[] divisionId, int[] departmentId, int[] sectionId, System.DateTime dateAtt, bool haveImage)
        {
            return base.Channel.GetEmployeeListWithArrDateAsync(divisionId, departmentId, sectionId, dateAtt, haveImage);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetLeaveEmployeeListAsync(int[] divisionId, int[] departmentId, bool haveImage)
        {
            return base.Channel.GetLeaveEmployeeListAsync(divisionId, departmentId, haveImage);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListPaySlipAsync(int divisionId, int departmentId, int sectionId, System.DateTime dtGetData, bool haveImage)
        {
            return base.Channel.GetEmployeeListPaySlipAsync(divisionId, departmentId, sectionId, dtGetData, haveImage);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.PositionInfo[]> GetAllPositionInfosAsync()
        {
            return base.Channel.GetAllPositionInfosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeWithPositionAndDepartmentAsync(int divisionId, System.Nullable<int> departmentId, System.Nullable<int> sectionId, ServiceEz.PositionInfo[] listPositionId)
        {
            return base.Channel.GetEmployeeWithPositionAndDepartmentAsync(divisionId, departmentId, sectionId, listPositionId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo> GetEmployeeInfoByCardIdAsync(string cardId)
        {
            return base.Channel.GetEmployeeInfoByCardIdAsync(cardId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.WorkScheduleInfo[]> SyncWorkScheduleAsync(ServiceEz.WorkScheduleInfo[] list, string token)
        {
            return base.Channel.SyncWorkScheduleAsync(list, token);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.TimeAttendenInfo[]> GetTimeAttendenInfosAsync(string employeeId, int year, int month)
        {
            return base.Channel.GetTimeAttendenInfosAsync(employeeId, year, month);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTimeAttendenAsync(ServiceEz.TimeAttenden timeAttenden)
        {
            return base.Channel.UpdateTimeAttendenAsync(timeAttenden);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateWorkScheduleAsync(ServiceEz.WorkScheduleInfo scheduleInfo, string token)
        {
            return base.Channel.UpdateWorkScheduleAsync(scheduleInfo, token);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeNotInListAsync(string[] employees)
        {
            return base.Channel.GetEmployeeNotInListAsync(employees);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeInListAsync(string[] listEmployeeCode)
        {
            return base.Channel.GetEmployeeInListAsync(listEmployeeCode);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetAllEmployeeInListHasImageAsync(string[] listEmployeeCode)
        {
            return base.Channel.GetAllEmployeeInListHasImageAsync(listEmployeeCode);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeChangeDeptAsync(System.DateTime fromDate)
        {
            return base.Channel.GetEmployeeChangeDeptAsync(fromDate);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeePropation[]> GetEmployeePropationAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId)
        {
            return base.Channel.GetEmployeePropationAsync(fromDate, toDate, divisionId, departmentId, sectionId, employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeePropation[]> GetEmployeeNotHavingPropationAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId)
        {
            return base.Channel.GetEmployeeNotHavingPropationAsync(fromDate, toDate, divisionId, departmentId, sectionId, employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeTerminate[]> GetEmployeeTerminateAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId)
        {
            return base.Channel.GetEmployeeTerminateAsync(fromDate, toDate, divisionId, departmentId, sectionId, employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeTerminate[]> GetEmployeePrivateLeaveWithoutReportAsync(System.DateTime fromDate, System.DateTime toDate, int divisionId, int departmentId, int sectionId, string employeeId)
        {
            return base.Channel.GetEmployeePrivateLeaveWithoutReportAsync(fromDate, toDate, divisionId, departmentId, sectionId, employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.TimeAttendenInfo[]> GetEmployeeWithoutScanCardAsync(System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetEmployeeWithoutScanCardAsync(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.LabourContractInfo> GetInfoLabourContractAsync(string employeeId, System.DateTime fromBusinessDate)
        {
            return base.Channel.GetInfoLabourContractAsync(employeeId, fromBusinessDate);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.LabourContractInfo> GetInfoLabourContractProbationAsync(string employeeId)
        {
            return base.Channel.GetInfoLabourContractProbationAsync(employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeJapanAsync()
        {
            return base.Channel.GetEmployeeJapanAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceEz.LeaveInfo[]> GetLeaveInfoInMonthAsync(System.DateTime month, int divisionId, int departmentId, int sectionId)
        {
            return base.Channel.GetLeaveInfoInMonthAsync(month, divisionId, departmentId, sectionId);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetAllEmployeeInListAsync(string[] listEmployeeCode)
        {
            return base.Channel.GetAllEmployeeInListAsync(listEmployeeCode);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.EmployeeInfo[]> GetEmployeeListAddTerminateOnMonthAsync(int divisionId, int departmentId, int sectionId, System.DateTime month, string employeeCode)
        {
            return base.Channel.GetEmployeeListAddTerminateOnMonthAsync(divisionId, departmentId, sectionId, month, employeeCode);
        }
        
        public System.Threading.Tasks.Task<double> CheckHd1WScheduleAsync(string employeeId, System.DateTime dtHd1)
        {
            return base.Channel.CheckHd1WScheduleAsync(employeeId, dtHd1);
        }
        
        public System.Threading.Tasks.Task<bool> CheckAccountAdAsync(string uName, string passWord)
        {
            return base.Channel.CheckAccountAdAsync(uName, passWord);
        }
        
        public System.Threading.Tasks.Task<ServiceEz.TimeAttenden[]> GetTimeAttendensAsync(System.DateTime dateTime)
        {
            return base.Channel.GetTimeAttendensAsync(dateTime);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceManPowerEz))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceManPowerEz))
            {
                return new System.ServiceModel.EndpointAddress("http://dmvnapp:1111/ServiceEz.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceManPowerEzClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceManPowerEz);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceManPowerEzClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceManPowerEz);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceManPowerEz,
        }
    }
}
